### ISSUE TITLE
Inverted I2S CLK needed

### ISSUE THREAD

**Issue by fcapano** [pixelmatix/SmartMatrix#116]
Commit fcca3a2906395612038c7664b857afcce8f5ce13 broke my RGB panel.

I don't know the rationale behind adding/reverting the inversion of the I2S CLK, but perhaps this could be toggled on/off with a SMARTMATRIX_ALLOCATE_BUFFERS(..., kMatrixOptions) flag?

I've attached a video with latest head before and after reverting the commit

![Before](https://user-images.githubusercontent.com/1628800/80277417-a9f18800-86e6-11ea-87c6-274194cf723a.gif)

![After](https://user-images.githubusercontent.com/1628800/80277413-a52cd400-86e6-11ea-9197-4c3947b42a8b.gif)

.

**Comment by embedded-creations** [comment]
Sure, can you give this a try?  https://github.com/pixelmatix/SmartMatrix/commit/42e9756038c6ad4e70d51c385099260a6f988a9d

**Comment by fcapano** [comment]
Well that was fast!
It's working now, thanks :)
