### ISSUE TITLE
P5 32x64 not correct display

### ISSUE THREAD

**Issue by gunaone** [pixelmatix/SmartMatrix#117]
i  was try with this p5 panel 32x64 but i got looklike this,
can anyone help,

![IMG_20200501_083741](https://user-images.githubusercontent.com/12540556/80774402-21139a00-8b87-11ea-98f9-62ddd02007c7.jpg)
![IMG_20200501_083751](https://user-images.githubusercontent.com/12540556/80774407-253fb780-8b87-11ea-8076-1474531c1cf9.jpg)
![IMG_20200501_083756](https://user-images.githubusercontent.com/12540556/80774415-28d33e80-8b87-11ea-84c3-39561404b356.jpg)

**Comment by embedded-creations** [comment]
what settings are you using at the top of your sketch?  can you post a photo of the back of the panel?  can you follow the instructions and run the multirowmapping sketch, and post a video of the sketch running from the beginning?

**Comment by gunaone** [comment]
i use example futuredemo 
with seting :
````
#define COLOR_DEPTH 24                  // known working: 24, 48 - If the sketch uses type `rgb24` directly, COLOR_DEPTH must be 24
const uint8_t kMatrixWidth = 64;        // known working: 32, 64, 96, 128
const uint8_t kMatrixHeight = 32;       // known working: 16, 32, 48, 64
const uint8_t kRefreshDepth = 36;       // known working: 24, 36, 48
const uint8_t kDmaBufferRows = 4;       // known working: 2-4, use 2 to save memory, more to keep from dropping frames and automatically lowering refresh rate
const uint8_t kPanelType = SMARTMATRIX_HUB75_32ROW_MOD16SCAN;   // use SMARTMATRIX_HUB75_16ROW_MOD8SCAN for common 16x32 panels
const uint8_t kMatrixOptions = (SMARTMATRIX_OPTIONS_NONE);      // see http://docs.pixelmatix.com/SmartMatrix for options
const uint8_t kBackgroundLayerOptions = (SM_BACKGROUND_OPTIONS_NONE);
const uint8_t kScrollingLayerOptions = (SM_SCROLLING_OPTIONS_NONE);
const uint8_t kIndexedLayerOptions = (SM_INDEXED_OPTIONS_NONE);

````

.

**Comment by embedded-creations** [comment]
> follow the instructions and run the multirowmapping sketch, and post a video of the sketch running from the beginning

**Comment by ondoteam** [comment]
Hello.

I am in troubles with a 64x32 panel too. It was working with PxMatrix. I am using a ESP32 wired directly to the panel.

This is my current config for MultiRowRefreshMapping:

```
#define GPIOPINOUT ESP32_FORUM_PINOUT_WITH_LATCH
#define MODE_MAP_REVERSE_ENGINEERING  0
#define MODE_MAP_TESTING              1

//#define SKETCH_MODE   MODE_MAP_REVERSE_ENGINEERING
#define SKETCH_MODE   MODE_MAP_TESTING

#define COLOR_DEPTH 24                  // known working: 24, 48 - If the sketch uses type `rgb24` directly, COLOR_DEPTH must be 24
const uint8_t kMatrixWidth = 64;        // known working: 16, 32, 48, 64
const uint8_t kMatrixHeight = 32;       // known working: 32, 64, 96, 128
const uint8_t kPanelType = SMARTMATRIX_HUB75_32ROW_MOD16SCAN;   // use SMARTMATRIX_HUB75_16ROW_MOD8SCAN for common 16x32 panels
const uint8_t kRefreshDepth = 36;       // known working: 24, 36, 48
const uint8_t kDmaBufferRows = 4;       // known working: 2-4, use 2 to save memory, more to keep from dropping frames and automatically lowering refresh rate
const uint8_t kMatrixOptions = (SMARTMATRIX_OPTIONS_NONE);      // see http://docs.pixelmatix.com/SmartMatrix for options
const uint8_t kBackgroundLayerOptions = (SM_BACKGROUND_OPTIONS_NONE);
```

It is what you need? Sorry for my bad english.

**Comment by embedded-creations** [comment]
@ondoteam What is not working?  Can you provide a video of the sketch running in MODE_MAP_REVERSE_ENGINEERING mode, and in MODE_MAP_TESTING mode?

**Comment by embedded-creations** [comment]
@ondoteam What is not working?  Can you provide a video of the sketch running in MODE_MAP_REVERSE_ENGINEERING mode, and in MODE_MAP_TESTING mode?

**Comment by ondoteam** [comment]
Sure. With the default values?

```
#if (SKETCH_MODE == MODE_MAP_REVERSE_ENGINEERING)
const uint8_t kMatrixWidth = 128;        // known working: 16, 32, 48, 64
const uint8_t kMatrixHeight = 4;       // known working: 32, 64, 96, 128
const uint8_t kPanelType = SMARTMATRIX_HUB75_4ROW_MOD2SCAN;   // Use this to reverse engineer mapping for a MOD2 panel
//const uint8_t kPanelType = SMARTMATRIX_HUB75_8ROW_MOD4SCAN;   // Use this to reverse engineer mapping for a MOD4 panel
#endif
```

**Comment by embedded-creations** [comment]
@ondoteam No, follow the instructions in the Sketch and pick the values that make sense for your panel.

I haven't seen any 128x64 panels that need this mapping feature, so I'm not sure that's what's causing the issue.  You may just want to run something simple like the Bitmaps sketch and take a video of that.

```
const uint8_t kMatrixWidth = 128;        // known working: 16, 32, 48, 64
const uint8_t kMatrixHeight = 64;       // known working: 32, 64, 96, 128
const uint8_t kPanelType = SMARTMATRIX_HUB75_64ROW_MOD32SCAN;
```
These values are what I would try first for your panel with the Bitmaps sketch

**Comment by ondoteam** [comment]
It is not a 128x64. It is 64x32 16SCAN

![photo_2020-05-11_22-42-36](https://user-images.githubusercontent.com/6900997/81615000-cc6aed00-93d8-11ea-900d-fb18639d8849.jpg)
![photo_2020-05-11_22-42-43](https://user-images.githubusercontent.com/6900997/81615007-cecd4700-93d8-11ea-9098-2a4de092831d.jpg)
![photo_2020-05-11_22-42-47](https://user-images.githubusercontent.com/6900997/81615013-d0970a80-93d8-11ea-89b3-50d0c2ef7034.jpg)

**Comment by ondoteam** [comment]
This is what I am getting for the following config in the bitmap example:

```
#include <SmartMatrix3.h>
#define GPIOPINOUT ESP32_FORUM_PINOUT_WITH_LATCH
#include "gimpbitmap.h"

// pixelmatix.c is a bitmap exported from GIMP without modification
#include "pixelmatix.c"

// colorwheel.c has been modified to use the gimp32x32bitmap struct
#include "colorwheel.c"

// chrome16 is a 16x16 pixel bitmap, exported from GIMP without modification
#include "chrome16.c"

#define COLOR_DEPTH 24                  // known working: 24, 48 - If the sketch uses type `rgb24` directly, COLOR_DEPTH must be 24
const uint8_t kMatrixWidth = 64;        // known working: 16, 32, 48, 64
const uint8_t kMatrixHeight = 32;       // known working: 32, 64, 96, 128
const uint8_t kRefreshDepth = 36;       // known working: 24, 36, 48
const uint8_t kDmaBufferRows = 4;       // known working: 2-4, use 2 to save memory, more to keep from dropping frames and automatically lowering refresh rate
const uint8_t kPanelType = SMARTMATRIX_HUB75_32ROW_MOD16SCAN; // use SMARTMATRIX_HUB75_16ROW_MOD8SCAN for common 16x32 panels, or use SMARTMATRIX_HUB75_64ROW_MOD32SCAN for common 64x64 panels
const uint8_t kMatrixOptions = (SMARTMATRIX_OPTIONS_NONE);      // see http://docs.pixelmatix.com/SmartMatrix for options
const uint8_t kBackgroundLayerOptions = (SM_BACKGROUND_OPTIONS_NONE);
```

![photo_2020-05-11_22-57-42](https://user-images.githubusercontent.com/6900997/81616261-1523a580-93db-11ea-9f02-fee38be86d4e.jpg)
![photo_2020-05-11_22-57-45](https://user-images.githubusercontent.com/6900997/81616263-1654d280-93db-11ea-9006-af7de48d1551.jpg)

**Comment by ondoteam** [comment]
There is a bad contact in the panel on OE (maybe this afternoon I forced the connector). I will check it tomorrow and update this issue. Thank you very much @embedded-creations

**Comment by ondoteam** [comment]
Hello. It is working now. Was a weak connection in the PCB. Finally I am using this config:

```
#include <SmartMatrix3.h>
#define GPIOPINOUT ESP32_FORUM_PINOUT_WITH_LATCH
#define COLOR_DEPTH 24                  // known working: 24, 48 - If the sketch uses type `rgb24` directly, COLOR_DEPTH must be 24
const uint8_t kMatrixWidth = 64;        // known working: 32, 64, 96, 128
const uint8_t kMatrixHeight = 32;       // known working: 16, 32, 48, 64
const uint8_t kRefreshDepth = 36;       // known working: 24, 36, 48
const uint8_t kDmaBufferRows = 4;       // known working: 2-4, use 2 to save memory, more to keep from dropping frames and automatically lowering refresh rate
const uint8_t kPanelType = SMARTMATRIX_HUB75_32ROW_MOD16SCAN; // use SMARTMATRIX_HUB75_16ROW_MOD8SCAN for common 16x32 panels, or use SMARTMATRIX_HUB75_64ROW_MOD32SCAN for common 64x64 panels
const uint8_t kMatrixOptions = (SMARTMATRIX_OPTIONS_NONE);      // see http://docs.pixelmatix.com/SmartMatrix for options
const uint8_t kBackgroundLayerOptions = (SM_BACKGROUND_OPTIONS_NONE);
const uint8_t kScrollingLayerOptions = (SM_SCROLLING_OPTIONS_NONE);
const uint8_t kIndexedLayerOptions = (SM_INDEXED_OPTIONS_NONE);

SMARTMATRIX_ALLOCATE_BUFFERS(matrix, kMatrixWidth, kMatrixHeight, kRefreshDepth, kDmaBufferRows, kPanelType, kMatrixOptions);
SMARTMATRIX_ALLOCATE_BACKGROUND_LAYER(backgroundLayer, kMatrixWidth, kMatrixHeight, COLOR_DEPTH, kBackgroundLayerOptions);
SMARTMATRIX_ALLOCATE_SCROLLING_LAYER(scrollingLayer, kMatrixWidth, kMatrixHeight, COLOR_DEPTH, kScrollingLayerOptions);
SMARTMATRIX_ALLOCATE_INDEXED_LAYER(indexedLayer, kMatrixWidth, kMatrixHeight, COLOR_DEPTH, kIndexedLayerOptions);

```

One more time, thank you very much @embedded-creations

**Comment by embedded-creations** [comment]
@ondoteam glad you got it working

@gunaone to help you I need to see a video with the results of the MultiRowMapping sketch.

**Comment by gunaone** [comment]
witchone..?
i cant find "MultiRowMapping"
https://github.com/pixelmatix/SmartMatrix/tree/master/examples

**Comment by embedded-creations** [comment]
@gunaone , sorry, it’s not available in the main repo, it’s on the “teensylc” branch, where you can test code that will be in the next SmartMatrix Library release

**Comment by erickimm13** [comment]
I have 32/16 with 1/2 scan rate. that when I run the MODE_MAP_REVERSE_ENGINEERING sketch 2 red dots and 2 purple come on.

![Screenshot (2)](https://user-images.githubusercontent.com/57026588/137555789-727c5b0c-cb79-40e6-bd3a-f09900c16c9d.png)

**Comment by erickimm13** [comment]
the yellow and white are showing 1 dot. I have different S2 that work fine with that sketch. but not this ones. see video.

**Comment by erickimm13** [comment]
![20211015_164259](https://user-images.githubusercontent.com/57026588/137557016-dfa5ccad-2147-448e-a188-4c1b7a303d15.jpg)
this is the back of the panel that shows 2 dots.

**Comment by erickimm13** [comment]
video of the panel that s2 that works with the same sketch

https://1drv.ms/v/s!Ao8XNpgZj8tdhp0vt3Udan0NviMmzw?e=f3Ku1w

**Comment by embedded-creations** [comment]
Hi, you're commenting on a closed issue.  This is a better topic to discuss in a new post in community.pixelmatix.com where you may be able to find someone else who has the same issue and maybe a fix.  I don't have any suggestions at the moment.,
