### ISSUE TITLE
32x32 /8 panel - getting multiple pixels in MultiRowRefreshMapping

### ISSUE THREAD

**Issue by tomtobback** [pixelmatix/SmartMatrix#128]
Hi, i have a 32x32 panel with 8 scan rate, which needs to be driven as 64x16 (that how it's working with another library). When i run the multirowrefreshmapping sketch, i have the entire rows 0 and row 8 lighting up in red, and it sets the pixels to black one by one ([video](https://photos.app.goo.gl/4dmRkZiX1D5sNCBW6)). My settings are:
```
const uint8_t kMatrixWidth = 64;        // known working: 16, 32, 48, 64
const uint8_t kMatrixHeight = 16;       // known working: 32, 64, 96, 128
const uint8_t kPanelType = SMARTMATRIX_HUB75_8ROW_MOD4SCAN;   // Use this to reverse engineer mapping for a MOD4 panel
```
I've also tried with SMARTMATRIX_HUB75_16ROW_MOD8SCAN and result is similar, a bar of 16 pixels moving horizontally.
I think i should be getting a single pixels moving around, any advice? Thanks.

**Comment by embedded-creations** [comment]
Do you mind reposting this in community.pixelmatix.com, where it's better to troubleshoot things like this, and we can leave Github Issues for bugs and feature requests?

Try this:
```
const uint8_t kMatrixWidth = 128;        // known working: 16, 32, 48, 64
const uint8_t kMatrixHeight = 8;       // known working: 32, 64, 96, 128
const uint8_t kPanelType = SMARTMATRIX_HUB75_16ROW_MOD8SCAN;   // Use this to reverse engineer mapping for a MOD4 panel
```
