### ISSUE TITLE
Pinout Doc

### ISSUE THREAD

**Issue by McCallisterMicro** [pixelmatix/SmartMatrix#144]
It'd be really nice if the Github wiki has a simple doc showing which Teensy pins are in use for SmartMatrix and which ones are not. I know I can figure it out from the code or looking at the PCB....but it'd be much more convenient to take a look at a wiki page.

**Comment by embedded-creations** [comment]
Documentation for the SmartLED Shield Hardware is hosted on another site: [SmartMatrix Docs](http://docs.pixelmatix.com/SmartMatrix/shieldref.html)

You can get to the hardware documentation for your shield by typing in the URL printed on the board and on the packaging.

I added a note and link in a couple places in the Wiki and in the SmartMatrix Library README so now hopefully it's easier to find when starting from GitHub
