### ISSUE TITLE
Lost few pixels in same place

### ISSUE THREAD

**Issue by m0raco** [pixelmatix/SmartMatrix#148]
Hi
Please could you help finding solution with such result? Pixels in black cells are showing in places as drawn. I cannot find solution. Much appreciation if you could help me! 👍
![image](https://user-images.githubusercontent.com/84351992/118554634-60009780-b76a-11eb-864d-164493a63dad.png)

**Comment by embedded-creations** [comment]
This is more appropriate for community.pixelmatix.com, assuming you're using SmartMatrix Library.  There's not nearly enough info here for me to understand the problem or help you.
