### ISSUE TITLE
Wiring a Teensy 4.1 without SmartLED Shield

### ISSUE THREAD

**Issue by DeltaW0x** [pixelmatix/SmartMatrix#173]
Does anybody have to some sort of documentation on how to wire a HUB75 matrix to a Teensy 4.1 without using a SmartLED Shield. I've recently transitioned from the ESP32 DMA HUB75 library, where I could define which pins I wanted to use. I can't seem to find how to do the same here though

**Comment by embedded-creations** [comment]
It’s unfortunately not possible on the Teensy 4, see details here: https://github.com/pixelmatix/SmartMatrix/wiki/MatrixHardware-Header

**Comment by DeltaW0x** [comment]
Alright, thank you, I didn't notice that
