### ISSUE TITLE
FeatureDemo.ino:6:31: fatal error: SmartMatrix_16x32.h: No such file or directory

### ISSUE THREAD

**Issue by ners11** [pixelmatix/SmartMatrix#21]
Please help me.
![2015-07-09 18 47 44](https://cloud.githubusercontent.com/assets/12465264/8599811/333d1a5c-266b-11e5-8eda-238030db1adb.png)

**Comment by embedded-creations** [comment]
It doesn't look like you have the SmartMatrix_16x32 library installed properly.  Do you see SmartMatrix_16x32 in your Arduino File->Example or Sketch->Include Library menus?

Installation instructions are here:
http://docs.pixelmatix.com/SmartMatrix/#software-and-teensy-setup

**Comment by ners11** [comment]
Yes, I do.

**Comment by jasoncoon** [comment]
Please enable verbose compilation output in Arduino, and then copy and paste the entire output to pastebin: http://pastebin.com

File->Preferences->Show verbose output during: Tick box for compilation

**Comment by jasoncoon** [comment]
Also, make sure you've restarted the Arduino IDE since you installed the library.  And I'd recommend updating to the latest version of the Arduino IDE (1.6.5): https://www.arduino.cc/en/Main/Software

**Comment by ners11** [comment]
http://pastebin.com/TqsUBAy7

**Comment by ners11** [comment]
All works, thanks for the help !
