### ISSUE TITLE
MatrixForeground bugs for width > 32

### ISSUE THREAD

**Issue by ecurtz** [pixelmatix/SmartMatrix#29]
Most of the MatrixForeground methods are hard coded to only operate on the first uint32 of the array i.e. the first screen segment for wider displays. I may take a look at fixing them because it isn't much code, but here's an issue for it just in case it takes me a while.

**Comment by embedded-creations** [comment]
Hi Eli, SmartMatrix Library 3.0 adds support for wider displays, you should work from the 3.0 branch.  It's days away from a pre-release.  Take a look at the draft MIGRATION.md document for some more details.
https://github.com/pixelmatix/SmartMatrix/tree/sm3.0
