### ISSUE TITLE
1/4 scan mode

### ISSUE THREAD

**Issue by happycodefarm** [pixelmatix/SmartMatrix#34]
Would it be possible to implement a 1/4 scan mod for the 16x32 outdoor hub75 matrix ?

Regards,

HCF

**Comment by embedded-creations** [comment]
Yes, I have a sample of an indoor 1/4 scan 16x32, and it's on my list though low priority.

If you're comfortable modifying the library yourself, I think I made it pretty easy to do so, just look for where DIV16 and DIV8 options are defined and used and add a DIV4.  Post here or on our forum if you need help: community.pixelmatix.com

**Comment by embedded-creations** [comment]
Do you have a link to purchase the outdoor hub75 matrix you have?  If it's cheap I might pick one up as a reference

**Comment by embedded-creations** [comment]
Also, I checked our your Psychedelic Pixels project, you might be interested in the port of Fadecandy to SmartMatrix, if you haven't seen it already - you can stream visuals from Processing to a matrix.  I haven't advertised it much yet as the documentation isn't done:
https://github.com/pixelmatix/SmartMatrix_Fadecandy

**Comment by embedded-creations** [comment]
This is a really old issue, but just in case someone's still looking at it, search for MultiRowRefreshMapping in community.pixelmatix.com
