### ISSUE TITLE
Clock with animated gifs playing behind

### ISSUE THREAD

**Issue by Dan7766** [pixelmatix/SmartMatrix#39]
Not really an issue but hoping you can help..

Im wanting to make a clock that has the time displayed while playing animated gifs at the same time behind the time maybe one every 30 seconds or so.. Would this be difficult to achieve ? Some pointers on where to start would be very much appreciated if you have the time.

Thanks
Daniel

**Comment by embedded-creations** [comment]
Hi Dan, do you mind posting this to our community?  It's a better fit there as like you said, this isn't an issue with the code.  Thanks!

community.pixelmatix.com

**Comment by Dan7766** [comment]
no problem..
