### ISSUE TITLE
PLay 128x32 animated GIF 

### ISSUE THREAD

**Issue by pinballsp** [pixelmatix/SmartMatrix#43]
Hello.

I need play videos with 128x32 resolution. I have do the animated GIF, but when I config kMatrixWidth with 128 and run, screen show message "No gifs directory".

With same SD card, same files, if I coinfig kMatrixWidth with 32 or 64, then play video but only 32x32, 4 times in screen and only part of the animation screen of the animated GIF.

So, how may I config software to play 128x32 animated GIF videos ?.
My led panels are two P2.5, 64x32 piexel, Scan 1/16 chained.

Thank you and kind regards.

**Comment by embedded-creations** [comment]
closing duplicate issue
