### ISSUE TITLE
Compatibility with Teensy 3.6

### ISSUE THREAD

**Issue by nicshackle** [pixelmatix/SmartMatrix#45]
Before I embark on a project, I'm wanting to check if this library is compatible with the Teensy 3.5 or 3.6? 

Thanks!

**Comment by embedded-creations** [comment]
Good timing, as of this week I added Teensy 3.5/3.6 compatibility.  It hasn't been packaged up into a release yet, that will come tomorrow hopefully, but you can pull the latest from the master branch and get Teensy 3.5/3.6 compatibility.
