### ISSUE TITLE
Arranging panels in zigzag pattern

### ISSUE THREAD

**Issue by nicshackle** [pixelmatix/SmartMatrix#46]
I have 8 16x32 panels arranged in the following pattern (note I've also called `matrix.setRotation(rotation90)`):

[imgur images](https://imgur.com/a/301N2)

However, the third row is mirrored (it's meant to read 'KLIP'). I am currently using `SMARTMATRIX_OPTIONS_C_SHAPE_STACKING`, but have also tried `SMARTMATRIX_OPTIONS_NONE` and `SMARTMATRIX_OPTIONS_BOTTOM_TO_TOP_STACKING` (and combinations of those).

Is there any way I can mirror the third row in software?

**Comment by embedded-creations** [comment]
Hi Nic, you must be one of the first people to try stacking more than two rows together (or the first to complain about it), I found a bug in the code and fixed it.  It will be in the next release, but hopefully you can make this change in your local library to get your display working in the meantime:

https://github.com/pixelmatix/SmartMatrix/commit/189bb985d68e0532186f6de6630f2ed7e24830f6
