### ISSUE TITLE
defaultBrightness calculated incorrectly in FeatureDemo.ino

### ISSUE THREAD

**Issue by drogge** [pixelmatix/SmartMatrix#56]
The parentheses in the two lines that do brightness calculation in FeatureDemo.ino are in the wrong place:

const int defaultBrightness = 100*(255/100);    // full brightness
//const int defaultBrightness = 15*(255/100);    // dim: 15% brightness

should be:

const int defaultBrightness = (100*255)/10);    // full brightness
//const int defaultBrightness = (15*255)/100;    // dim: 15% brightness

Or you can just leave out the parentheses.

**Comment by embedded-creations** [comment]
thanks!
