### ISSUE TITLE
Colors are wrong. Very yellow.

### ISSUE THREAD

**Issue by FuzzyWobble** [pixelmatix/SmartMatrix#59]
Sadly, my colors are incorrect with 64x64 on teensy3.6 and SmartLEDShieldV4.h

They are very very yellow-ish. Not at all matching the colors from my GIFs. 

Any idea how to fix such issue?

Thanks x100

**Comment by embedded-creations** [comment]
Are you missing a color channel (e.g. R, G, or B) in your GIFs, or are some of the channels swapped?

**Comment by mcaustin2019** [comment]
Try changing to the following:

void drawPixelCallback(int16_t x, int16_t y, uint8_t blue, uint8_t green, uint8_t red) {
backgroundLayer.drawPixel(x, y, {red, green, blue});

My gifs were yellow and this worked for me.
