### ISSUE TITLE
Smartmatrix shield v4 and Teensey 3.6 not working on 64x32 display

### ISSUE THREAD

**Issue by dhpete** [pixelmatix/SmartMatrix#60]
Hey, guys. I bought some 64x32 panels from amazon, got a teensey 3.6 and smartshield v4, hooked everything up( I think, the correct way) and nothing. Plenty of power, code compiles( using the Feature Demo sketch) Loader seems to program, but display does not come on. Without the Teensey/Shield installed, you can touch the pins on the matrix and get a reaction, so I dont think its DOA. Even tried 2 different panels with the same results. Is there something I am missing? Sorry if its a dumb question, but Im a total NOOB to this matrix thing. Any help would be great.

**Comment by embedded-creations** [comment]
Did you remove the comment at the top of the sketch to tell the library you're using SmartLED Shield V4?  (This is done by default now but I don't know what version you're using)

It should look like this at the top:
```
#include <SmartLEDShieldV4.h>  // comment out this line for if you're not using SmartLED Shield V4 hardware (this line needs to be before #include <SmartMatrix3.h>)
#include <SmartMatrix3.h>
```

**Comment by dhpete** [comment]
Thanks, Louis. Mine was uncommented. After pulling the shield (while it was on) I now get a 16x16 green section in the lower right corner. Well, its a start :). If I upload the FastLED functions sketch, the display goes off, reload the other sketch and back to the green spot. Sorry for bothering you guys...this might take me a while.

**Comment by embedded-creations** [comment]
Can you upload a picture of your your shield, wiring, power?

Can you take a picture of the back of one of the panels showing any pinout diagrams that are on the board?

**Comment by dhpete** [comment]
![img_20181219_102022](https://user-images.githubusercontent.com/45876124/50230901-93615100-037b-11e9-9965-17822b1f0804.jpg)


![img_20181219_102710](https://user-images.githubusercontent.com/45876124/50230733-47161100-037b-11e9-9f33-b1cd54695dc0.jpg)

![img_20181219_102651](https://user-images.githubusercontent.com/45876124/50230679-2352cb00-037b-11e9-9715-68a1357fda46.jpg)

![img_20181219_102522](https://user-images.githubusercontent.com/45876124/50230466-b808f900-037a-11e9-8043-0e0fd61ac6aa.jpg)


![img_20181219_102542](https://user-images.githubusercontent.com/45876124/50230512-cbb45f80-037a-11e9-95cb-f29495f3dd5f.jpg)



Sorry for the crappy pics. Power is from a 5v 60a power supply. 2 64x32 panels but only one connected. Thought I would get one working, then go through the process for 64x64. No labels on the pin outs but I went by this https://cdn-learn.adafruit.com/downloads/pdf/32x16-32x32-rgb-led-matrix.pdf

**Comment by embedded-creations** [comment]
Try running this precompiled sketch.  Unzip, drag the .hex into the TeensyLoader window, and make sure the name in the lower section of TeensyLoader updates, then press the button on the Teensy 3.6 and make sure it loads.

![screen shot 2018-12-19 at 4 17 41 pm](https://user-images.githubusercontent.com/1514796/50232725-9e32da80-03a9-11e9-9674-8072dfef731c.png)

[FeatureDemo-Teensy3.6-32x32-V4.ino.hex.zip](https://github.com/pixelmatix/SmartMatrix/files/2695649/FeatureDemo-Teensy3.6-32x32-V4.ino.hex.zip)

**Comment by dhpete** [comment]
This is what I got
![img_20181219_114130](https://user-images.githubusercontent.com/45876124/50234241-38335c80-0383-11e9-9d4e-66baac13b301.jpg)
The diagonal lines are from my camera...not visible to the eye

**Comment by marcmerlin** [comment]
@dhpete  just to confirm, I bought a 64x32 panel from amazon like yours, plugged in a teensy 3.6 into the same shield you bought, and it just worked. Louis is already helping you, but just confirming that this exact setup should work fine.
As a slight note, usually it's better to ask for help on a forum ( https://community.pixelmatix.com ) than open an issue unless you're pretty sure that you found an issue with the library.

**Comment by dhpete** [comment]
About to just call this project a bust. Searched the forums and tried a few things, but still nothing. At least the clock module and remote will be here today (sarcasm). Seems the chances of getting 2 bad panels is low( although possible) Teensey seems to work for other applications and mounted to the shield, all GPIO seem to function. Im at a loss. Was looking forward to running Aurora on this. Thanks for all the help, just not sure where to go from here.

**Comment by dhpete** [comment]
Thanks. Tested GPIO on Teensey, and GPIO on the shield with Teensey on
board. Not sure how to rest the ribbon/matrix connector output, but seems
like all pins on the board work. Tried one panel with a Arduino Mega using
the RGB matrix panel sketch and couldnt get that to work either. Could be
my code there, or I have 2 bad panels. Im not too great at this
troubleshooting. So far my Arduino/Pi experience has been you plug it in,
and it works. Thanks for all your help, just wish I could get this up and
running as I really wanted to use Aurora.

**Comment by embedded-creations** [comment]
> So far my Arduino/Pi experience has been you plug it in, and it works

Yes, that's the goal of the SmartLED Shield.

Have you tried connecting both with directly plugging in the SmartLED Shield to the panel, and with using the pins and ribbon cable to connect between shield and panel?

How did you test the GPIO signals going through the SmartLED Shield?  There are level shifting buffers on the shield, and if one of those had a loose connection, the signals may not be working properly on the HUB75 connector side.  A good test you could do with just a multimeter is to have the Teensy toggle the pins between 0/1 at a slow rate, so you can easily see them change with the multimeter.  Plug the male-male pins into the HUB75 connector on the shield so you can probe them.  Toggle pins and look for the change with the multimeter.  Especially look for Teensy pin 3 to toggle the "LT" signal on the HUB75 connector, and Teensy pin 14 to toggle the "CK" signal as that's where I think the issues could be based on your troubleshooting so far.

Sorry for the continued hassle with this.

**Comment by embedded-creations** [comment]
And if you'd rather just get a replacement board instead of continuing to troubleshoot, as I said before I encourage you to request a replacement Shield from where you bought your SmartLED Shield.
