### ISSUE TITLE
USE SmartMatrix with P10 module

### ISSUE THREAD

**Issue by MohamadAlsadi** [pixelmatix/SmartMatrix#87]
hello my friend 

I am working on drive P10 module display ( 1 color)  via ESP32

I need library for drive 2 pcs from P10 module (64x16 display every one 32x16) 

please help me

**Comment by MohamadAlsadi** [comment]
the link for ESP is 
https://www.shenzhen2u.com/NodeMCU-32S

I need show and scroll text 
please help me about ESP pins that must used and code for show and scroll text

**Comment by embedded-creations** [comment]
The ESP32 port isn't finished and isn't well supported.  You can find some information on our forum here, and you can post questions there too if you don't see what you're looking for:

https://community.pixelmatix.com/t/smartmatrix-library-esp32-port/272/
