### ISSUE TITLE
Calling matrix.begin() causes Serial1 not work anymore

### ISSUE THREAD

**Issue by LucasBruder** [pixelmatix/SmartMatrix#9]
I've included code to test this out:

Receiving code:
#include "SmartMatrix_32x32.h"
SmartMatrix matrix;

void setup()  
{
  Serial1.begin(115200);
  Serial.begin(9600);
}

void loop() 
{
  if(Serial1.available())
  {
    char c = Serial1.read();
    Serial.print(c);
  }
  
  if(Serial.available())
  {
    char c = Serial.read();
    Serial.print(c);
    matrix.begin();
  }
}

Sender code:

void setup()  
{
  Serial1.begin(115200);
  Serial.begin(9600);
}

int count = 0;

void loop() 
{
      String x = "Hi there. This is a test message send to the Teensy please.\n";
      Serial1.println(count);
      count++;
      for(int i = 0; i < x.length(); i++)
        Serial1.print(x.charAt(i));
        
      delay(2000);
}

Note that when you enter in character into Serial, it calls matrix.begin() and all messages after that call are never received. I've also contacted Paul S on the Teensy forum (http://forum.pjrc.com/threads/26325-Issues-w-SmartMatrix-Library-Teensy-3-1)

**Comment by embedded-creations** [comment]
Hi @LucasBruder did you ever get this working?

**Comment by embedded-creations** [comment]
closed due to inactivity
