### ISSUE TITLE
esp32 rgb panel scrolling not working for 4 panels

### ISSUE THREAD

**Issue by nareshmekh3** [pixelmatix/SmartMatrix#96]
**Devices used:**
1. Esp32
2. P6 - INDOOR - RGB LED Matrix Panel - 1/16 Scan - 32x32 Pixels - 192mm x 192mm - HUB75
3. power supply 5v 60 amps

**Pinout connection:**
R0 --->  2 
G0 --->  15
B0 --->  4
R1 --->  16 
G1 --->  27
B1 --->  17
E --->   12 
A --->   5
B --->   18
C --->   19 
D --->   21
CLK ---> 22
STD ---> 26 
OE --->  25
GND ---> gnd

Here i am using basic example FeatureDemo with 4 panels so i changed the kMatrixWidth to 128 and kMatrixHeight = 32. Remaining code i did not changed. 
The issue is scrolling text is visible in the first panel but not visible in the remaining panels.

so can any one suggest me how to over come this issue and please check the pin connection for esp32 and rgb panel.

below i am attaching the output image.

![IMG_20191224_173415_resized_20191224_053926195](https://user-images.githubusercontent.com/36899436/71412692-d5029700-2674-11ea-84a1-1d98c69ab47a.jpg)

**Comment by embedded-creations** [comment]
If you post issues like this over at community.pixelmatix.com you may get more responses.

I don't think it's an ESP32 pinout/wiring issue as you're getting a valid image on the first panel.  Can you show a picture of the back of the panels?

Are the panels all the same?  What happens if you swap the first panel that's working with panel 2 or 3?

**Comment by nareshmekh3** [comment]
Hi, I am using same 32x32  RGB LED Matrix panel, i tried with swapping the panels but even it is giving same issues. 

below i am sharing picture of the back of the panels.
![IMG_20191226_112653](https://user-images.githubusercontent.com/36899436/71460752-35a7e600-27d3-11ea-96ab-2c95b65f406b.jpg)

**Comment by embedded-creations** [comment]
Maybe try swapping the ribbon cables around?  You know the gray cable is working, I’m not so sure about the rainbow cables. 

Also try the sketch configured for 32x32. The first panel should propagate a similar image to the second panel

**Comment by nareshmekh3** [comment]
Thank you so much for your support, its working its cable issue i tried with another cable it was working fine.

![IMG_20191226_183346](https://user-images.githubusercontent.com/36899436/71477301-3bbbb800-280f-11ea-9e05-c22459b95b76.jpg)
