### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tarbear123** [pixelmatix/SmartMatrix#99]
whenever I go to upload it, I get this error:

Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Uno"

Multiple libraries were found for "SmartMatrix3.h"
In file included from C:\Users\taran\OneDrive\Documents\Arduino\libraries\SmartMatrix3\src/SmartMatrix3.h:175:0,

 Used: C:\Users\taran\OneDrive\Documents\Arduino\libraries\SmartMatrix3
                 from C:\Users\taran\OneDrive\Desktop\SmartMatrix-3.2.0\examples\Bitmaps\Bitmaps.ino:10:

C:\Users\taran\OneDrive\Documents\Arduino\libraries\SmartMatrix3\src/SmartMatrix_Impl.h:26:10: fatal error: DMAChannel.h: No such file or directory

 #include "DMAChannel.h"

          ^~~~~~~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

I can't seem to add DMAChannel to my library, plz help
and I'm only using smartmatrix in this scetch

**Comment by embedded-creations** [comment]
> Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Uno"

You want to select the Teensy board you’re using, not an the default Arduino Uno board
